### ISSUE TITLE
Add Publications to Publications Page

### ISSUE THREAD

**Issue by harshsikka** [Manifold-Computing/webpage#2]

**Comment by harshsikka** [comment]
The Publications page needs someone to format and add the following references, in chronological order (most recent at the top)

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=fNTB_VoAAAAJ&citation_for_view=fNTB_VoAAAAJ:IjCSPb-OGe4C

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=fNTB_VoAAAAJ&citation_for_view=fNTB_VoAAAAJ:_FxGoFyzp5QC

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=fNTB_VoAAAAJ&citation_for_view=fNTB_VoAAAAJ:WF5omc3nYNoC

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=fNTB_VoAAAAJ&citation_for_view=fNTB_VoAAAAJ:W7OEmFMy1HYC

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=fNTB_VoAAAAJ&citation_for_view=fNTB_VoAAAAJ:8k81kl-MbHgC

https://scholar.google.com/citations?view_op=view_citation&hl=en&user=fNTB_VoAAAAJ&citation_for_view=fNTB_VoAAAAJ:2osOgNQ5qMEC

**Comment by harshsikka** [comment]
Assigning @sidhsikka1

**Comment by sidhsikka1** [comment]
Added these publications to page
